# SPDX-License-Identifier: MIT
# Copyright (c) 2026 CrashWise Contributors
"""AI Report Synthesizer — generates professional vulnerability disclosure
reports and structured finding models from crash data, RCA, and verification results.

Supports multiple output formats tailored to specific platforms:
    • ``hackerone`` — HackerOne markdown with impact & reproduction steps.
    • ``bugcrowd`` — Bugcrowd template with severity justification.
    • ``kernel`` — Linux kernel mailing list style (plain text, technical).
    • ``generic`` — Platform-agnostic Markdown suitable for any tracker.

Also provides structured finding generation (:func:`generate_finding_report`)
exporting type-safe :class:`FindingReport` models containing bug class, affected
function, source location (file:line), crash input SHA256 hash, and 4-tier severity.
"""

from __future__ import annotations

import contextlib
import hashlib
import re
from pathlib import Path
from typing import Any

from crashwise.agents.triage.analyzer import classify_crash_severity
from crashwise.core.ai_provider import get_provider
from crashwise.core.logging import get_logger
from crashwise.core.models import (
    CrashSeverity,
    FindingReport,
    FindingReproductionMetadata,
)

log = get_logger(__name__)

# ── Platform-specific templates ──────────────────────────────────────────────

_H1_TEMPLATE = """\
# {title}

## Summary
{summary}

## Description
{description}

## Impact
{impact}

## Steps to Reproduce
{reproduction}

## Proof of Concept
```
{poc}
```

## Suggested Fix
```cpp
{patch}
```

## CVSS Vector
{cvss_vector}  (Base Score: {cvss_score})

## References
{references}

---
*Generated by CrashWise Autonomous Fuzzing Platform*
"""

_BUGCROWD_TEMPLATE = """\
# {title}

## Vulnerability Details
{description}

## Severity Justification
{severity_justification}

## Proof of Concept
{poc}

## Steps to Reproduce
{reproduction}

## Impact
{impact}

## Mitigation / Fix
```cpp
{patch}
```

## CVSS
{cvss_vector} — **{cvss_score}**

---
*Report generated by CrashWise*
"""

_KERNEL_TEMPLATE = """\
Subject: [PATCH] {title}

Hi maintainers,

CrashWise (an autonomous fuzzing platform) discovered the following
memory-safety issue in {target}:

{description}

## Root Cause Analysis
{root_cause}

## Proposed Patch
```diff
{patch}
```

## Verification
The patch was verified by re-running the fuzzer with the crash-triggering
seed for {timeout}s.  Result: {verification_status}.

## CVSS Estimate
{cvss_vector} (score: {cvss_score})

Please review and apply if appropriate.

---
CrashWise Contributors
"""

_GENERIC_TEMPLATE = """\
# Vulnerability Report: {title}

## Overview
| Field | Value |
|-------|-------|
| **Bug Type** | {bug_type} |
| **Severity** | {severity} ({severity_score}/10) |
| **CVSS** | {cvss_vector} ({cvss_score}) |
| **CWE** | {cwe} |
| **Status** | {verification_status} |

## Description
{description}

## Root Cause
{root_cause}

## Reproduction
{reproduction}

## Suggested Patch
```cpp
{patch}
```

## Verification Log
```
{verification_stdout}
```

---
*Generated by CrashWise v0.1.0*
"""

_FRAME_RE = re.compile(
    r"#0\s+0x[0-9a-fA-F]+(?:\s+in|\s+\([^)]+\)\s+in|\s+in\s+)?\s+([a-zA-Z0-9_:]+)(?:\s+(?:at|\/)\s*(\S+:\d+))?",
)


# ── Structured Finding Generator ─────────────────────────────────────────────


def generate_finding_report(
    crash_data: dict[str, Any],
    *,
    crash_file_bytes: bytes | None = None,
    crash_file_path: str | Path | None = None,
) -> FindingReport:
    """Generate a structured, type-safe finding report with SHA256 and severity metrics.

    Parameters
    ----------
    crash_data:
        Dictionary containing crash finding attributes.
    crash_file_bytes:
        Optional raw bytes of the minimized crash input to hash.
    crash_file_path:
        Optional path to minimized crash input file to hash.

    Returns
    -------
    FindingReport
        Structured finding report model.
    """
    crash_id = str(crash_data.get("crash_id") or "crash-finding-1")
    bug_class = str(crash_data.get("bug_type") or crash_data.get("bug_class") or "unknown")

    # 1. Compute SHA256 hex digest of minimized crash input file
    crash_input_hash = ""
    if crash_file_bytes is not None:
        crash_input_hash = hashlib.sha256(crash_file_bytes).hexdigest()
    elif crash_file_path:
        p = Path(crash_file_path)
        if p.is_file():
            with contextlib.suppress(Exception):
                crash_input_hash = hashlib.sha256(p.read_bytes()).hexdigest()
    if not crash_input_hash:
        raw_hash = crash_data.get("crash_input_hash") or crash_data.get("seed_hash")
        if raw_hash:
            crash_input_hash = str(raw_hash)
        elif crash_data.get("seed_path"):
            sp = Path(str(crash_data["seed_path"]))
            if sp.is_file():
                with contextlib.suppress(Exception):
                    crash_input_hash = hashlib.sha256(sp.read_bytes()).hexdigest()
    if not crash_input_hash:
        # Fallback hash over crash_id + bug_class
        crash_input_hash = hashlib.sha256(f"{crash_id}:{bug_class}".encode()).hexdigest()

    # 2. Extract affected function & source location (file:line)
    affected_func = str(
        crash_data.get("affected_function")
        or crash_data.get("target_function")
        or crash_data.get("vulnerable_function")
        or ""
    )
    source_loc = str(crash_data.get("source_location") or "")

    if not affected_func or not source_loc:
        raw_trace = str(crash_data.get("stack_trace") or crash_data.get("asan_output") or "")
        match = _FRAME_RE.search(raw_trace)
        if match:
            if not affected_func:
                affected_func = match.group(1).strip()
            if not source_loc and match.group(2):
                source_loc = match.group(2).strip()

    if not source_loc:
        sf = crash_data.get("source_file") or crash_data.get("file")
        ln = crash_data.get("line_number") or crash_data.get("line")
        if sf and ln:
            source_loc = f"{sf}:{ln}"
        elif sf:
            source_loc = str(sf)

    # 3. 4-Tier Severity Classification
    sev_level, sev_score, primitive = classify_crash_severity(
        bug_type=bug_class,
        asan_output=str(crash_data.get("asan_output") or ""),
        registers=crash_data.get("registers") if isinstance(crash_data.get("registers"), dict) else None,
        raw_text=str(crash_data.get("raw_text") or crash_data.get("stack_trace") or ""),
        gdb_output=str(crash_data.get("gdb_output") or ""),
    )

    # If explicit severity override provided
    if "severity_score" in crash_data:
        with contextlib.suppress(ValueError, TypeError):
            sev_score = float(crash_data["severity_score"])
    if "severity" in crash_data:
        raw_sev = str(crash_data["severity"]).lower()
        if raw_sev in [s.value for s in CrashSeverity]:
            sev_level = CrashSeverity(raw_sev)

    # 4. Reproduction Metadata
    reproduction = FindingReproductionMetadata(
        target_linked=bool(crash_data.get("target_linked", False)),
        reproduced=bool(crash_data.get("crash_reproduced", crash_data.get("reproduced", False))),
        asan_matched=bool(crash_data.get("asan_matched", crash_data.get("asan_class_matched", False))),
        function_matched=bool(crash_data.get("function_matched", False)),
        reproducer_code=str(crash_data.get("poc_code") or crash_data.get("reproducer_code") or ""),
        compilation_command=str(crash_data.get("compilation_command") or ""),
        fidelity_score=float(crash_data.get("reproduction_fidelity") or crash_data.get("fidelity_score") or 0.0),
    )

    return FindingReport(
        crash_id=crash_id,
        bug_class=bug_class,
        affected_function=affected_func,
        source_location=source_loc,
        crash_input_hash=crash_input_hash,
        severity_score=round(sev_score, 1),
        severity_level=sev_level,
        primitive=primitive,
        reproduction=reproduction,
        root_cause=str(crash_data.get("root_cause") or ""),
        suggested_patch=str(crash_data.get("suggested_patch") or crash_data.get("patch") or ""),
        target_name=str(crash_data.get("target_name") or ""),
        target_repo=str(crash_data.get("target_repo") or ""),
    )


# ── Public API ───────────────────────────────────────────────────────────────


async def generate_report(
    crash_data: dict[str, Any],
    *,
    fmt: str = "generic",
    provider: Any | None = None,
) -> dict[str, str]:
    """Synthesize a professional vulnerability report.

    Parameters
    ----------
    crash_data:
        Must contain keys: ``bug_type``, ``severity``, ``severity_score``,
        ``vulnerability_type``, ``root_cause``, ``suggested_patch``,
        ``verification_status``, ``stack_trace``, ``target_name``,
        ``target_repo``.
    fmt:
        One of ``hackerone``, ``bugcrowd``, ``kernel``, ``generic``.
    provider:
        Optional AI inference provider for enhanced prose.

    Returns
    -------
    dict with keys ``title``, ``body``, ``platform``.
    """
    log.info("report_generator.start", fmt=fmt, target=crash_data.get("target_name"))

    # Normalize format.
    fmt = fmt.lower().strip()
    template = {
        "hackerone": _H1_TEMPLATE,
        "bugcrowd": _BUGCROWD_TEMPLATE,
        "kernel": _KERNEL_TEMPLATE,
    }.get(fmt, _GENERIC_TEMPLATE)

    # Build context blocks.
    title = _build_title(crash_data)
    summary = _build_summary(crash_data)
    description = _build_description(crash_data)
    impact = _build_impact(crash_data)
    reproduction = _build_reproduction(crash_data)
    poc = crash_data.get("stack_trace", "")[:2000]
    patch = crash_data.get("suggested_patch", "")
    cvss_vector = crash_data.get("cvss_vector", "N/A")
    cvss_score = crash_data.get("cvss_score", "N/A")
    references = crash_data.get("target_repo", "")
    severity_justification = _build_severity_justification(crash_data)
    root_cause = crash_data.get("root_cause", "")
    verification_status = crash_data.get("verification_status", "pending")
    verification_stdout = crash_data.get("verification_stdout", "")
    timeout = crash_data.get("timeout_seconds", 60)
    target = crash_data.get("target_name", "unknown")
    bug_type = crash_data.get("bug_type", "unknown")
    severity = crash_data.get("severity", "unknown")
    severity_score = crash_data.get("severity_score", 0)
    cwe = crash_data.get("vulnerability_type", "unknown")

    # Try AI enhancement if provider is available.
    provider = provider or get_provider()
    if await provider.health_check():
        description = await _enhance_with_ai(
            provider,
            "Write a concise vulnerability description for a bug bounty report",
            description,
        )
        impact = await _enhance_with_ai(
            provider,
            "Write a business-impact paragraph for a bug bounty report",
            impact,
        )

    body = template.format(
        title=title,
        summary=summary,
        description=description,
        impact=impact,
        reproduction=reproduction,
        poc=poc,
        patch=patch or "No patch available",
        cvss_vector=cvss_vector,
        cvss_score=cvss_score,
        references=references,
        severity_justification=severity_justification,
        root_cause=root_cause,
        verification_status=verification_status,
        verification_stdout=verification_stdout,
        timeout=timeout,
        target=target,
        bug_type=bug_type,
        severity=severity,
        severity_score=severity_score,
        cwe=cwe,
    )

    log.info("report_generator.complete", fmt=fmt, title=title)
    return {
        "title": title,
        "body": body,
        "platform": fmt,
    }


# ── Internal helpers ───────────────────────────────────────────────────────


def _build_title(data: dict[str, Any]) -> str:
    target = data.get("target_name", "Unknown")
    bug = data.get("bug_type", "memory-safety bug")
    return f"[{target}] {bug.replace('-', ' ').title()}"


def _build_summary(data: dict[str, Any]) -> str:
    target = data.get("target_name", "the target")
    bug = data.get("bug_type", "a memory-safety bug")
    sev = data.get("severity", "unknown")
    return (
        f"A {bug} was discovered in {target} during autonomous fuzzing. "
        f"Severity: {sev}."
    )


def _build_description(data: dict[str, Any]) -> str:
    root_cause = data.get("root_cause", "")
    bug = data.get("bug_type", "memory-safety bug")
    target = data.get("target_name", "the target")
    if root_cause:
        return (
            f"During fuzzing of {target}, a {bug} was triggered. "
            f"Root cause: {root_cause}"
        )
    return f"A {bug} was discovered in {target} during fuzzing."


def _build_impact(data: dict[str, Any]) -> str:
    bug = data.get("bug_type", "")
    if "use-after-free" in bug or "double-free" in bug:
        return (
            "An attacker with network access could potentially achieve "
            "remote code execution or cause a denial of service by "
            "corrupting heap metadata."
        )
    if "buffer-overflow" in bug or "out-of-bounds" in bug:
        return (
            "Successful exploitation could lead to information disclosure, "
            "arbitrary code execution, or denial of service depending on "
            "the affected buffer location (stack vs heap)."
        )
    if "null-pointer" in bug or "null-deref" in bug:
        return "Denial of service via segmentation fault."
    return "Impact depends on the attack surface of the affected component."


def _build_reproduction(data: dict[str, Any]) -> str:
    seed = data.get("seed_path", "N/A")
    harness = data.get("harness_path", "N/A")
    return (
        f"1. Build the target with ASAN/UBSAN.\n"
        f"2. Run the fuzzer harness: `{harness}`\n"
        f"3. Feed the crash seed: `{seed}`\n"
        f"4. Observe the crash."
    )


def _build_severity_justification(data: dict[str, Any]) -> str:
    score = data.get("severity_score", 0)
    bug = data.get("bug_type", "")
    if score >= 9:
        return (
            f"Critical severity: {bug} with exploitability score {score}/10. "
            "Trivially exploitable with full write-what-where or code execution primitives."
        )
    if score >= 7:
        return (
            f"High severity: {bug} with exploitability score {score}/10. "
            "Exploitable with effort (may require heap groom, UAF, or ASLR bypass)."
        )
    if score >= 4:
        return (
            f"Medium severity: {bug} with exploitability score {score}/10. "
            "Out-of-bounds read or information disclosure."
        )
    return (
        f"Low severity: {bug} with exploitability score {score}/10. "
        "Limited impact (denial-of-service via null dereference or divide-by-zero)."
    )


async def _enhance_with_ai(
    provider: Any,
    instruction: str,
    fallback: str,
) -> str:
    """Ask the AI provider to improve prose; fall back on failure."""
    try:
        result = await provider.analyze(
            f"{instruction}\n\nDraft:\n{fallback}"
        )
        enhanced = str(result.get("root_cause", ""))
        if enhanced and len(enhanced) > 20:
            return enhanced
    except Exception:
        log.debug("report_generator.ai_enhance_failed")
    return str(fallback)


__all__ = [
    "generate_finding_report",
    "generate_report",
]
