# SPDX-License-Identifier: MIT
# Copyright (c) 2026 CrashWise Contributors
"""AI Report Synthesizer — generates professional vulnerability disclosure
reports from crash data, RCA, and verification results.

Supports multiple output formats tailored to specific platforms:
    • ``hackerone`` — HackerOne markdown with impact & reproduction steps.
    • ``bugcrowd`` — Bugcrowd template with severity justification.
    • ``kernel`` — Linux kernel mailing list style (plain text, technical).
    • ``generic`` — Platform-agnostic Markdown suitable for any tracker.

Usage::

    from crashwise.agents.reporting.generator import generate_report

    report = await generate_report(
        crash_data={...},
        format="hackerone",
    )
"""

from __future__ import annotations

from typing import Any

from crashwise.core.ai_provider import get_provider
from crashwise.core.logging import get_logger

log = get_logger(__name__)

# ── Platform-specific templates ──────────────────────────────────────────────

_H1_TEMPLATE = """\
# {title}

## Summary
{summary}

## Description
{description}

## Impact
{impact}

## Steps to Reproduce
{reproduction}

## Proof of Concept
```
{poc}
```

## Suggested Fix
```cpp
{patch}
```

## CVSS Vector
{cvss_vector}  (Base Score: {cvss_score})

## References
{references}

---
*Generated by CrashWise Autonomous Fuzzing Platform*
"""

_BUGCROWD_TEMPLATE = """\
# {title}

## Vulnerability Details
{description}

## Severity Justification
{severity_justification}

## Proof of Concept
{poc}

## Steps to Reproduce
{reproduction}

## Impact
{impact}

## Mitigation / Fix
```cpp
{patch}
```

## CVSS
{cvss_vector} — **{cvss_score}**

---
*Report generated by CrashWise*
"""

_KERNEL_TEMPLATE = """\
Subject: [PATCH] {title}

Hi maintainers,

CrashWise (an autonomous fuzzing platform) discovered the following
memory-safety issue in {target}:

{description}

## Root Cause Analysis
{root_cause}

## Proposed Patch
```diff
{patch}
```

## Verification
The patch was verified by re-running the fuzzer with the crash-triggering
seed for {timeout}s.  Result: {verification_status}.

## CVSS Estimate
{cvss_vector} (score: {cvss_score})

Please review and apply if appropriate.

---
CrashWise Contributors
"""

_GENERIC_TEMPLATE = """\
# Vulnerability Report: {title}

## Overview
| Field | Value |
|-------|-------|
| **Bug Type** | {bug_type} |
| **Severity** | {severity} ({severity_score}/10) |
| **CVSS** | {cvss_vector} ({cvss_score}) |
| **CWE** | {cwe} |
| **Status** | {verification_status} |

## Description
{description}

## Root Cause
{root_cause}

## Reproduction
{reproduction}

## Suggested Patch
```cpp
{patch}
```

## Verification Log
```
{verification_stdout}
```

---
*Generated by CrashWise v0.1.0*
"""


# ── Public API ───────────────────────────────────────────────────────────────


async def generate_report(
    crash_data: dict[str, Any],
    *,
    fmt: str = "generic",
    provider: Any | None = None,
) -> dict[str, str]:
    """Synthesize a professional vulnerability report.

    Parameters
    ----------
    crash_data:
        Must contain keys: ``bug_type``, ``severity``, ``severity_score``,
        ``vulnerability_type``, ``root_cause``, ``suggested_patch``,
        ``verification_status``, ``stack_trace``, ``target_name``,
        ``target_repo``.
    fmt:
        One of ``hackerone``, ``bugcrowd``, ``kernel``, ``generic``.
    provider:
        Optional AI inference provider for enhanced prose.

    Returns
    -------
    dict with keys ``title``, ``body``, ``platform``.
    """
    log.info("report_generator.start", fmt=fmt, target=crash_data.get("target_name"))

    # Normalize format.
    fmt = fmt.lower().strip()
    template = {
        "hackerone": _H1_TEMPLATE,
        "bugcrowd": _BUGCROWD_TEMPLATE,
        "kernel": _KERNEL_TEMPLATE,
    }.get(fmt, _GENERIC_TEMPLATE)

    # Build context blocks.
    title = _build_title(crash_data)
    summary = _build_summary(crash_data)
    description = _build_description(crash_data)
    impact = _build_impact(crash_data)
    reproduction = _build_reproduction(crash_data)
    poc = crash_data.get("stack_trace", "")[:2000]
    patch = crash_data.get("suggested_patch", "")
    cvss_vector = crash_data.get("cvss_vector", "N/A")
    cvss_score = crash_data.get("cvss_score", "N/A")
    references = crash_data.get("target_repo", "")
    severity_justification = _build_severity_justification(crash_data)
    root_cause = crash_data.get("root_cause", "")
    verification_status = crash_data.get("verification_status", "pending")
    verification_stdout = crash_data.get("verification_stdout", "")
    timeout = crash_data.get("timeout_seconds", 60)
    target = crash_data.get("target_name", "unknown")
    bug_type = crash_data.get("bug_type", "unknown")
    severity = crash_data.get("severity", "unknown")
    severity_score = crash_data.get("severity_score", 0)
    cwe = crash_data.get("vulnerability_type", "unknown")

    # Try AI enhancement if provider is available.
    provider = provider or get_provider()
    if await provider.health_check():
        description = await _enhance_with_ai(
            provider,
            "Write a concise vulnerability description for a bug bounty report",
            description,
        )
        impact = await _enhance_with_ai(
            provider,
            "Write a business-impact paragraph for a bug bounty report",
            impact,
        )

    body = template.format(
        title=title,
        summary=summary,
        description=description,
        impact=impact,
        reproduction=reproduction,
        poc=poc,
        patch=patch or "No patch available",
        cvss_vector=cvss_vector,
        cvss_score=cvss_score,
        references=references,
        severity_justification=severity_justification,
        root_cause=root_cause,
        verification_status=verification_status,
        verification_stdout=verification_stdout,
        timeout=timeout,
        target=target,
        bug_type=bug_type,
        severity=severity,
        severity_score=severity_score,
        cwe=cwe,
    )

    log.info("report_generator.complete", fmt=fmt, title=title)
    return {
        "title": title,
        "body": body,
        "platform": fmt,
    }


# ── Internal helpers ───────────────────────────────────────────────────────


def _build_title(data: dict[str, Any]) -> str:
    target = data.get("target_name", "Unknown")
    bug = data.get("bug_type", "memory-safety bug")
    return f"[{target}] {bug.replace('-', ' ').title()}"


def _build_summary(data: dict[str, Any]) -> str:
    target = data.get("target_name", "the target")
    bug = data.get("bug_type", "a memory-safety bug")
    sev = data.get("severity", "unknown")
    return (
        f"A {bug} was discovered in {target} during autonomous fuzzing. "
        f"Severity: {sev}."
    )


def _build_description(data: dict[str, Any]) -> str:
    root_cause = data.get("root_cause", "")
    bug = data.get("bug_type", "memory-safety bug")
    target = data.get("target_name", "the target")
    if root_cause:
        return (
            f"During fuzzing of {target}, a {bug} was triggered. "
            f"Root cause: {root_cause}"
        )
    return f"A {bug} was discovered in {target} during fuzzing."


def _build_impact(data: dict[str, Any]) -> str:
    bug = data.get("bug_type", "")
    if "use-after-free" in bug or "double-free" in bug:
        return (
            "An attacker with network access could potentially achieve "
            "remote code execution or cause a denial of service by "
            "corrupting heap metadata."
        )
    if "buffer-overflow" in bug or "out-of-bounds" in bug:
        return (
            "Successful exploitation could lead to information disclosure, "
            "arbitrary code execution, or denial of service depending on "
            "the affected buffer location (stack vs heap)."
        )
    if "null-pointer" in bug:
        return "Denial of service via segmentation fault."
    return "Impact depends on the attack surface of the affected component."


def _build_reproduction(data: dict[str, Any]) -> str:
    seed = data.get("seed_path", "N/A")
    harness = data.get("harness_path", "N/A")
    return (
        f"1. Build the target with ASAN/UBSAN.\n"
        f"2. Run the fuzzer harness: `{harness}`\n"
        f"3. Feed the crash seed: `{seed}`\n"
        f"4. Observe the crash."
    )


def _build_severity_justification(data: dict[str, Any]) -> str:
    score = data.get("severity_score", 0)
    bug = data.get("bug_type", "")
    if score >= 8:
        return (
            f"Critical severity: {bug} with exploitability score {score}/10. "
            "Trivially exploitable with full read/write primitives."
        )
    if score >= 5:
        return (
            f"High severity: {bug} with exploitability score {score}/10. "
            "Exploitable with effort (may require infoleak or ASLR bypass)."
        )
    return (
        f"Low/Medium severity: {bug} with exploitability score {score}/10. "
        "Limited impact or difficult to exploit in practice."
    )


async def _enhance_with_ai(
    provider: Any,
    instruction: str,
    fallback: str,
) -> str:
    """Ask the AI provider to improve prose; fall back on failure."""
    try:
        result = await provider.analyze(
            f"{instruction}\n\nDraft:\n{fallback}"
        )
        enhanced = result.get("root_cause", "")
        if enhanced and len(enhanced) > 20:
            return enhanced
    except Exception:
        log.debug("report_generator.ai_enhance_failed")
    return fallback


__all__ = ["generate_report"]
