# SPDX-License-Identifier: MIT
# Copyright (c) 2026 CrashWise Contributors
"""``read_coverage_data`` activity — reads raw coverage data from disk.

A trivial I/O activity that maintains Temporal workflow determinism by
keeping filesystem reads out of the workflow body. The workflow calls
this before ``analyze_coverage_activity`` to load the coverage summary
generated by ``execute_fuzzing``.
"""

from __future__ import annotations

from pathlib import Path

from temporalio import activity

from crashwise.core.logging import get_logger

log = get_logger(__name__)

# Cap the coverage data to 1 MB to avoid overwhelming the activity payload.
_MAX_COVERAGE_DATA_BYTES: int = 1_048_576


@activity.defn(name="read_coverage_data")
async def read_coverage_data(payload: dict) -> str:
    """Read coverage data file and return its contents as a string.

    Parameters
    ----------
    payload:
        Dict with a ``path`` key pointing to the coverage summary file.

    Returns
    -------
    Coverage data text, or empty string if the file is missing/unreadable.
    """
    path_str = payload.get("path", "")
    if not path_str:
        return ""

    path = Path(path_str)
    if not path.exists():
        log.debug("read_coverage_data.file_missing", path=path_str)
        return ""

    try:
        data = path.read_text(encoding="utf-8", errors="replace")
        if len(data) > _MAX_COVERAGE_DATA_BYTES:
            # Truncate from the beginning, keeping the most recent data.
            data = data[-_MAX_COVERAGE_DATA_BYTES:]
        log.info(
            "read_coverage_data.success",
            path=path_str,
            size=len(data),
        )
        return data
    except OSError as exc:
        log.warning("read_coverage_data.read_failed", path=path_str, error=str(exc))
        return ""


__all__ = ["read_coverage_data"]
